#!/bin/bash
home=$(dirname $(readlink -f "$0"))
ver=`$1/scripts/linuxcnc_var LINUXCNCVERSION`
ver=`expr $ver : '\([0-9]*\.[0-9]*\.[0-9]*\)'`
if [ $? -ne 0 ]
then 
   echo LinuxCNC not found
   exit 1
fi
echo "//LinuxCNC version = $ver" > version.h
echo "//File auto generated by version.sh" >> version.h
IFS='.'; arr=($ver); unset IFS;
echo "#define MAJOR_VER ${arr[0]}" >> version.h
echo "#define MINOR_VER ${arr[1]}" >> version.h

exit 0
