#!/bin/bash
home=$(dirname $(readlink -f "$0"))
<<<<<<< Updated upstream
if [ -z "$LINUXCNC" ]
then
	echo "You must define a variable called LINUXCNC with the path to your LinuxCNC source. See readme.txt for more details"
	exit -1
fi
echo "using LinuxCNC directory: $LINUXCNC"
ver=`"linuxcnc_var" LINUXCNCVERSION`
echo "ver = $ver"
=======
ver=`$EMC2_HOME/scripts/linuxcnc_var LINUXCNCVERSION`
>>>>>>> Stashed changes
ver=`expr $ver : '\([0-9]*\.[0-9]*\.[0-9]*\)'`
if [ $? -ne 0 ]
then 
   echo LinuxCNC not found
   exit 1
fi
echo "//LinuxCNC version = $ver" > version.h
echo "//File auto generated by version.sh" >> version.h
IFS='.'; arr=($ver); unset IFS;
echo "#define LINUXCNC_VER ((${arr[0]} * 10000) + (${arr[1]} * 100) + ${arr[2]})" >> version.h
echo "#define LINUXCNC_PRE_JOINTS (LINUXCNC_VER < 20800)  //This is when axes and joints were separated" >> version.h
echo "#define LINUXCNC_MULTI_SPINDLE (LINUXCNC_VER >= 20800)  //This is when axes and joints were separated" >> version.h

cd "$1"
branch=`git rev-parse --short HEAD`
targ="$home/../../../bin/plugins/i386-linux-gnu/linuxcncserver/how-to-build-cncremote-linuxcnc_$ver.txt"
echo "To download the source files for LinuxCNC:" > $targ
echo "git clone https://github.com/LinuxCNC/linuxcnc.git linuxcnc" >> $targ
echo "cd linuxcnc" >> $targ
echo "git checkout $branch" >> $targ
echo "Follow the build instructions at <http://linuxcnc.org/docs/devel/html/code/building-linuxcnc.html>" >> $targ
cd "$home"
branch=`git rev-parse --short HEAD`
echo "git clone https://github.com/sheetcam/CNCRemote.git cncremote" >> $targ
echo "cd cncremote" >> $targ
echo "git checkout $branch" >> $targ
echo "Install CodeBlocks <www.codeblocks.org>" >> $targ
echo "Run CodeBlocks from a LinuxCNC rip-environment" >> $targ
echo "Using CodeBlocks open cncremote/drivers/linuxcnc/server/linuxcncserver.cbp and build it." >> $targ
echo "For more information on building CNCRemote see cncremote/README.txt" >> $targ
exit 0
